// <auto-generated />
using System;
using Business;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Business.Migrations
{
    [DbContext(typeof(Web_Trung_GianContext))]
    [Migration("20240303165328_Init DB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Business.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3243),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Hoàng Minh Nguyệt",
                            password = "minhnguyet",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3244),
                            username = "minhnguyet"
                        },
                        new
                        {
                            id = 2,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3247),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Thùy Dương",
                            password = "thuyduong",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3248),
                            username = "thuyduong"
                        },
                        new
                        {
                            id = 3,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3252),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Lê Thạc Hoành",
                            password = "thachoanh",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3252),
                            username = "thachoanh"
                        },
                        new
                        {
                            id = 4,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3256),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Quang Vị",
                            password = "quangvi",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3256),
                            username = "quangvi"
                        },
                        new
                        {
                            id = 5,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3259),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Mạnh Cường",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3260),
                            username = "manhcuong"
                        },
                        new
                        {
                            id = 6,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3263),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Việt Hân",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3263),
                            username = "viethan"
                        },
                        new
                        {
                            id = 7,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3267),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Trung Hiếu",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3267),
                            username = "trunghieu"
                        },
                        new
                        {
                            id = 8,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3270),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Văn Tuấn",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3271),
                            username = "vantuan"
                        },
                        new
                        {
                            id = 9,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3274),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Ngô Gia Thiện",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3274),
                            username = "giathien"
                        },
                        new
                        {
                            id = 10,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3277),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Phan Thế Anh",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3278),
                            username = "theanh"
                        },
                        new
                        {
                            id = 11,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3281),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Ngọc Hoàng",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3282),
                            username = "ngochoang"
                        },
                        new
                        {
                            id = 12,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3286),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Quang Lộc",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3286),
                            username = "quangloc"
                        },
                        new
                        {
                            id = 13,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3290),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Hải Đan",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3290),
                            username = "haidan123"
                        },
                        new
                        {
                            id = 14,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3294),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Admin",
                            password = "admin",
                            phone = "0987654321",
                            role_id = 1,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3294),
                            username = "admin"
                        });
                });

            modelBuilder.Entity("Business.Models.Deposit", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.Property<int>("wallet_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Deposits");

                    b.HasData(
                        new
                        {
                            id = "1DY75F3K26T",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3396),
                            create_by = 1,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang chờ xác nhận",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3397),
                            update_by = 1,
                            wallet_id = 1
                        },
                        new
                        {
                            id = "2DI83A9M0P",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3402),
                            create_by = 2,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3403),
                            update_by = 2,
                            wallet_id = 2
                        },
                        new
                        {
                            id = "3DW29E6G3T",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3407),
                            create_by = 3,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "thành công",
                            status = "xác nhận thành công",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3407),
                            update_by = 3,
                            wallet_id = 3
                        },
                        new
                        {
                            id = "4DX64S7S9Y",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3411),
                            create_by = 4,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "thất bại",
                            status = "xác nhận thất bại",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3412),
                            update_by = 4,
                            wallet_id = 4
                        },
                        new
                        {
                            id = "5DB17K9Y8X",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3415),
                            create_by = 5,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "thành công",
                            status = "hoàn thành",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3415),
                            update_by = 5,
                            wallet_id = 5
                        },
                        new
                        {
                            id = "6DP96C3I5V",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3418),
                            create_by = 6,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang chờ xác nhận",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3419),
                            update_by = 6,
                            wallet_id = 6
                        },
                        new
                        {
                            id = "7DD50M1A7Q",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3422),
                            create_by = 7,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3423),
                            update_by = 7,
                            wallet_id = 7
                        },
                        new
                        {
                            id = "8DR05R0J6X",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3425),
                            create_by = 8,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "thành công",
                            status = "xác nhận thành công",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3426),
                            update_by = 8,
                            wallet_id = 8
                        },
                        new
                        {
                            id = "9DG63J9F6H",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3429),
                            create_by = 9,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "thất bại",
                            status = "xác nhận thất bại",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3430),
                            update_by = 9,
                            wallet_id = 9
                        },
                        new
                        {
                            id = "10DL81T2G8Z",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3432),
                            create_by = 10,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "thành công",
                            status = "hoàn thành",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3433),
                            update_by = 10,
                            wallet_id = 10
                        },
                        new
                        {
                            id = "11DF85R8K6S",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3436),
                            create_by = 11,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang chờ xác nhận",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3437),
                            update_by = 11,
                            wallet_id = 11
                        },
                        new
                        {
                            id = "12DM14S4P4V",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3439),
                            create_by = 12,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3440),
                            update_by = 12,
                            wallet_id = 12
                        },
                        new
                        {
                            id = "13DP76J5J1R",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3443),
                            create_by = 13,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "thành công",
                            status = "xác nhận thành công",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3443),
                            update_by = 13,
                            wallet_id = 13
                        },
                        new
                        {
                            id = "14DS57C4B8K",
                            amount = 10000,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3447),
                            create_by = 14,
                            description = "nạp tiền",
                            is_delete = false,
                            state = "thất bại",
                            status = "xác nhận thất bại",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3447),
                            update_by = 14,
                            wallet_id = 14
                        });
                });

            modelBuilder.Entity("Business.Models.DepositResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<string>("deposit_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("type_transaction")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("DepositResponses");

                    b.HasData(
                        new
                        {
                            id = 1,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3665),
                            create_by = 14,
                            deposit_id = "1DY75F3K26T",
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3666),
                            update_by = 14
                        },
                        new
                        {
                            id = 2,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3670),
                            create_by = 14,
                            deposit_id = "2DI83A9M0P",
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3671),
                            update_by = 14
                        },
                        new
                        {
                            id = 3,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3674),
                            create_by = 14,
                            deposit_id = "3DW29E6G3T",
                            description = "Giao dịch thành công",
                            is_delete = false,
                            state = "thành công",
                            status = "hoàn thành",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3675),
                            update_by = 14
                        },
                        new
                        {
                            id = 4,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3678),
                            create_by = 14,
                            deposit_id = "4DX64S7S9Y",
                            description = "Giao dịch thất bại",
                            is_delete = false,
                            state = "thất bại",
                            status = "xác nhận thất bại",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3679),
                            update_by = 14
                        },
                        new
                        {
                            id = 5,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3682),
                            create_by = 14,
                            deposit_id = "5DB17K9Y8X",
                            description = "Giao dịch thành công",
                            is_delete = false,
                            state = "thành công",
                            status = "hoàn thành",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3683),
                            update_by = 14
                        },
                        new
                        {
                            id = 6,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3686),
                            create_by = 14,
                            deposit_id = "6DP96C3I5V",
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3687),
                            update_by = 14
                        },
                        new
                        {
                            id = 7,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3690),
                            create_by = 14,
                            deposit_id = "7DD50M1A7Q",
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3691),
                            update_by = 14
                        },
                        new
                        {
                            id = 8,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3693),
                            create_by = 14,
                            deposit_id = "8DR05R0J6X",
                            description = "Giao dịch thành công",
                            is_delete = false,
                            state = "thành công",
                            status = "hoàn thành",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3694),
                            update_by = 14
                        },
                        new
                        {
                            id = 9,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3697),
                            create_by = 14,
                            deposit_id = "9DG63J9F6H",
                            description = "Giao dịch thất bại",
                            is_delete = false,
                            state = "thất bại",
                            status = "xác nhận thất bại",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3698),
                            update_by = 14
                        },
                        new
                        {
                            id = 10,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3701),
                            create_by = 14,
                            deposit_id = "10DL81T2G8Z",
                            description = "Giao dịch thành công",
                            is_delete = false,
                            state = "thành công",
                            status = "hoàn thành",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3701),
                            update_by = 14
                        },
                        new
                        {
                            id = 11,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3704),
                            create_by = 14,
                            deposit_id = "11DF85R8K6S",
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3705),
                            update_by = 14
                        },
                        new
                        {
                            id = 12,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3707),
                            create_by = 14,
                            deposit_id = "12DM14S4P4V",
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3708),
                            update_by = 14
                        },
                        new
                        {
                            id = 13,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3711),
                            create_by = 14,
                            deposit_id = "13DP76J5J1R",
                            description = "Giao dịch thành công",
                            is_delete = false,
                            state = "thành công",
                            status = "hoàn thành",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3712),
                            update_by = 14
                        },
                        new
                        {
                            id = 14,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3715),
                            create_by = 14,
                            deposit_id = "14DS57C4B8K",
                            description = "Giao dịch thất bại",
                            is_delete = false,
                            state = "thất bại",
                            status = "xác nhận thất bại",
                            type_transaction = "nạp tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3716),
                            update_by = 14
                        });
                });

            modelBuilder.Entity("Business.Models.IntermediateOrder", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("buy_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("buy_user")
                        .HasColumnType("int");

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float>("earn_amount")
                        .HasColumnType("real");

                    b.Property<float>("fee_rate")
                        .HasColumnType("real");

                    b.Property<bool>("fee_type")
                        .HasColumnType("bit");

                    b.Property<string>("hidden_content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<bool>("is_public")
                        .HasColumnType("bit");

                    b.Property<string>("link_product")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<float>("payment_amount")
                        .HasColumnType("real");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("IntermediateOrders");

                    b.HasData(
                        new
                        {
                            id = "FjNnwZdR",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3847),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3854),
                            create_by = 1,
                            description = "tài khoản Office ",
                            earn_amount = 950f,
                            fee_rate = 0.05f,
                            fee_type = true,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = false,
                            link_product = "#",
                            name = "Tài Khoản Office",
                            payment_amount = 1000f,
                            price = 1000f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3855),
                            update_by = 1
                        },
                        new
                        {
                            id = "tCWyd9xS",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3857),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3860),
                            create_by = 2,
                            description = "tài khoản GBT ",
                            earn_amount = 500f,
                            fee_rate = 0.05f,
                            fee_type = false,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = true,
                            link_product = "#",
                            name = "Tài Khoản GBT",
                            payment_amount = 525f,
                            price = 500f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3861),
                            update_by = 1
                        },
                        new
                        {
                            id = "Kk3us7mV",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3864),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3870),
                            create_by = 3,
                            description = "tài khoản Facebook ",
                            earn_amount = 1425f,
                            fee_rate = 0.05f,
                            fee_type = true,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = false,
                            link_product = "#",
                            name = "Tài Khoản Facebook",
                            payment_amount = 1500f,
                            price = 1500f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3873),
                            update_by = 1
                        },
                        new
                        {
                            id = "yh2LnbGk",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3875),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3877),
                            create_by = 4,
                            description = "tài khoản Game ",
                            earn_amount = 2000f,
                            fee_rate = 0.05f,
                            fee_type = false,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = true,
                            link_product = "#",
                            name = "Tài Khoản Game",
                            payment_amount = 2100f,
                            price = 2000f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3878),
                            update_by = 1
                        },
                        new
                        {
                            id = "6zqRwHEu",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3879),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3882),
                            create_by = 5,
                            description = "tài khoản Unity ",
                            earn_amount = 475f,
                            fee_rate = 0.05f,
                            fee_type = true,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = false,
                            link_product = "#",
                            name = "Tài Khoản Unity",
                            payment_amount = 500f,
                            price = 500f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3882),
                            update_by = 1
                        },
                        new
                        {
                            id = "I1mJYvoA",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3884),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3886),
                            create_by = 6,
                            description = "tài khoản Microsoft",
                            earn_amount = 1000f,
                            fee_rate = 0.05f,
                            fee_type = false,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = true,
                            link_product = "#",
                            name = "Tài Khoản Microsoft",
                            payment_amount = 1050f,
                            price = 1000f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3887),
                            update_by = 1
                        },
                        new
                        {
                            id = "OnvTBGFk",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3888),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3893),
                            create_by = 7,
                            description = "tài khoản Spine ",
                            earn_amount = 1425f,
                            fee_rate = 0.05f,
                            fee_type = true,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = true,
                            link_product = "#",
                            name = "Tài Khoản Spine",
                            payment_amount = 1500f,
                            price = 1500f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3894),
                            update_by = 1
                        },
                        new
                        {
                            id = "a2D1PC0L",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3897),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3901),
                            create_by = 8,
                            description = "tài khoản Adobephotoshop ",
                            earn_amount = 2000f,
                            fee_rate = 0.05f,
                            fee_type = false,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = true,
                            link_product = "#",
                            name = "Tài Khoản Adobephotoshop",
                            payment_amount = 2100f,
                            price = 2000f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3902),
                            update_by = 1
                        },
                        new
                        {
                            id = "Q9XWqMr3",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3905),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3909),
                            create_by = 9,
                            description = "tài khoản Ai ",
                            earn_amount = 475f,
                            fee_rate = 0.05f,
                            fee_type = true,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = true,
                            link_product = "#",
                            name = "Tài Khoản Ai",
                            payment_amount = 500f,
                            price = 500f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3910),
                            update_by = 1
                        },
                        new
                        {
                            id = "hwPm5QZR",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3931),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3934),
                            create_by = 10,
                            description = "tài khoản Gmail ",
                            earn_amount = 1000f,
                            fee_rate = 0.05f,
                            fee_type = false,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = false,
                            link_product = "#",
                            name = "Tài Khoản Gmail",
                            payment_amount = 1050f,
                            price = 1000f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3935),
                            update_by = 1
                        },
                        new
                        {
                            id = "fDlco4Ii",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3937),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3940),
                            create_by = 11,
                            description = "tài khoản Git ",
                            earn_amount = 1425f,
                            fee_rate = 0.05f,
                            fee_type = true,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = true,
                            link_product = "#",
                            name = "Tài Khoản Git",
                            payment_amount = 1500f,
                            price = 1500f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3941),
                            update_by = 1
                        },
                        new
                        {
                            id = "LziBV2fq",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3942),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3944),
                            create_by = 12,
                            description = "tài khoản Netflix ",
                            earn_amount = 2000f,
                            fee_rate = 0.05f,
                            fee_type = false,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = true,
                            link_product = "#",
                            name = "Tài Khoản Netflix",
                            payment_amount = 2100f,
                            price = 2000f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3945),
                            update_by = 1
                        },
                        new
                        {
                            id = "2n3mMgFy",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3947),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3949),
                            create_by = 13,
                            description = "tài khoản Youtube ",
                            earn_amount = 475f,
                            fee_rate = 0.05f,
                            fee_type = true,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = true,
                            link_product = "#",
                            name = "Tài Khoản Vip Youtube",
                            payment_amount = 500f,
                            price = 500f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3950),
                            update_by = 1
                        },
                        new
                        {
                            id = "eSgvtQo6",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3952),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3954),
                            create_by = 14,
                            description = "tài khoản Duolingo ",
                            earn_amount = 1000f,
                            fee_rate = 0.05f,
                            fee_type = false,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = false,
                            link_product = "#",
                            name = "Tài Khoản Duolingo",
                            payment_amount = 1050f,
                            price = 1000f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3955),
                            update_by = 1
                        },
                        new
                        {
                            id = "wFzU6Nvj",
                            buy_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3956),
                            contact = "facebook, mess,zalo",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3959),
                            create_by = 10,
                            description = "tài khoản Coursera ",
                            earn_amount = 950f,
                            fee_rate = 0.05f,
                            fee_type = true,
                            hidden_content = "tài khoản: account, mật khẩu: password",
                            is_delete = false,
                            is_public = true,
                            link_product = "#",
                            name = "Tài Khoản Coursera",
                            payment_amount = 1000f,
                            price = 1000f,
                            state = "đang xử lí",
                            status = "mới tạo",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3959),
                            update_by = 1
                        });
                });

            modelBuilder.Entity("Business.Models.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("desctiption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            desctiption = "Admin"
                        },
                        new
                        {
                            id = 2,
                            desctiption = "User"
                        });
                });

            modelBuilder.Entity("Business.Models.Wallet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<int>("balance")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("account_id");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            id = 1,
                            account_id = 1,
                            balance = 20000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3331),
                            update_by = 1
                        },
                        new
                        {
                            id = 2,
                            account_id = 2,
                            balance = 10000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3334),
                            update_by = 2
                        },
                        new
                        {
                            id = 3,
                            account_id = 3,
                            balance = 20000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3336),
                            update_by = 3
                        },
                        new
                        {
                            id = 4,
                            account_id = 4,
                            balance = 10000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3338),
                            update_by = 4
                        },
                        new
                        {
                            id = 5,
                            account_id = 5,
                            balance = 20000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3340),
                            update_by = 5
                        },
                        new
                        {
                            id = 6,
                            account_id = 6,
                            balance = 10000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3342),
                            update_by = 6
                        },
                        new
                        {
                            id = 7,
                            account_id = 7,
                            balance = 20000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3344),
                            update_by = 7
                        },
                        new
                        {
                            id = 8,
                            account_id = 8,
                            balance = 10000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3346),
                            update_by = 8
                        },
                        new
                        {
                            id = 9,
                            account_id = 9,
                            balance = 20000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3348),
                            update_by = 9
                        },
                        new
                        {
                            id = 10,
                            account_id = 10,
                            balance = 10000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3350),
                            update_by = 10
                        },
                        new
                        {
                            id = 11,
                            account_id = 11,
                            balance = 20000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3352),
                            update_by = 11
                        },
                        new
                        {
                            id = 12,
                            account_id = 12,
                            balance = 10000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3354),
                            update_by = 12
                        },
                        new
                        {
                            id = 13,
                            account_id = 13,
                            balance = 20000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3356),
                            update_by = 13
                        },
                        new
                        {
                            id = 14,
                            account_id = 14,
                            balance = 1000000,
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3358),
                            update_by = 14
                        });
                });

            modelBuilder.Entity("Business.Models.Withdrawal", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("bank_name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("bank_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("bank_user")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.Property<int>("wallet_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("wallet_id");

                    b.ToTable("Withdrawals");

                    b.HasData(
                        new
                        {
                            id = "1W0U5V1I0",
                            amount = 5000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Hoàng Minh Nguyệt",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3563),
                            create_by = 1,
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang chờ xác nhận",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3565),
                            update_by = 1,
                            wallet_id = 1
                        },
                        new
                        {
                            id = "2W4F4Y9E7",
                            amount = 1000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Nguyễn Thùy Dương",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3569),
                            create_by = 2,
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3570),
                            update_by = 2,
                            wallet_id = 2
                        },
                        new
                        {
                            id = "3W3C1J8P1",
                            amount = 5000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Lê Thạc Hoành",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3574),
                            create_by = 3,
                            is_delete = false,
                            state = "thành công",
                            status = "xác nhận thành công",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3575),
                            update_by = 3,
                            wallet_id = 3
                        },
                        new
                        {
                            id = "4W6O2Q2R4",
                            amount = 1000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Nguyễn Quang Vị",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3579),
                            create_by = 4,
                            is_delete = false,
                            state = "thất bại",
                            status = "xác nhận thất bại",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3579),
                            update_by = 4,
                            wallet_id = 4
                        },
                        new
                        {
                            id = "5W8O2W1A3",
                            amount = 5000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Nguyễn Mạnh Cường",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3583),
                            create_by = 5,
                            is_delete = false,
                            state = "thành công",
                            status = "hoàn thành",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3583),
                            update_by = 5,
                            wallet_id = 5
                        },
                        new
                        {
                            id = "6W2Z1O6B1",
                            amount = 1000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Nguyễn Việt Hân",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3587),
                            create_by = 6,
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang chờ xác nhận",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3587),
                            update_by = 6,
                            wallet_id = 6
                        },
                        new
                        {
                            id = "7W3T0N3S0",
                            amount = 5000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Nguyễn Trung Hiếu",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3591),
                            create_by = 7,
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3591),
                            update_by = 7,
                            wallet_id = 7
                        },
                        new
                        {
                            id = "8W4I2D8D0",
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Nguyễn Văn Tuấn",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3595),
                            create_by = 8,
                            is_delete = false,
                            state = "thành công",
                            status = "xác nhận thành công",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3595),
                            update_by = 8,
                            wallet_id = 8
                        },
                        new
                        {
                            id = "9W6H6F3O2",
                            amount = 5000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Ngô Gia Thiện",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3602),
                            create_by = 9,
                            is_delete = false,
                            state = "thất bại",
                            status = "xác nhận thất bại",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3603),
                            update_by = 9,
                            wallet_id = 9
                        },
                        new
                        {
                            id = "10W1B4L3R5",
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Phan Thế Anh",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3606),
                            create_by = 10,
                            is_delete = false,
                            state = "thành công",
                            status = "hoàn thành",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3607),
                            update_by = 10,
                            wallet_id = 10
                        },
                        new
                        {
                            id = "11W8I7T8V7",
                            amount = 5000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Nguyễn Ngọc Hoàng",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3611),
                            create_by = 11,
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xác nhận",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3612),
                            update_by = 11,
                            wallet_id = 11
                        },
                        new
                        {
                            id = "12W6M7E2D3",
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Nguyễn Quang Lộc",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3614),
                            create_by = 12,
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3615),
                            update_by = 12,
                            wallet_id = 12
                        },
                        new
                        {
                            id = "13W4Q0L0L6",
                            amount = 5000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Nguyễn Hải Đan",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3618),
                            create_by = 13,
                            is_delete = false,
                            state = "thành công",
                            status = "xác nhận thành công",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3619),
                            update_by = 13,
                            wallet_id = 13
                        },
                        new
                        {
                            id = "14W9C9M5F4",
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank Admin",
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3622),
                            create_by = 14,
                            is_delete = false,
                            state = "thất bại",
                            status = "xác nhận thất bại",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3622),
                            update_by = 14,
                            wallet_id = 14
                        });
                });

            modelBuilder.Entity("Business.Models.WithdrawalResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("type_transaction")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.Property<string>("withdrawal_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("WithdrawalResponses");

                    b.HasData(
                        new
                        {
                            id = 1,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3754),
                            create_by = 14,
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3755),
                            update_by = 14,
                            withdrawal_id = "1W0U5V1I0"
                        },
                        new
                        {
                            id = 2,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3759),
                            create_by = 14,
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3760),
                            update_by = 14,
                            withdrawal_id = "2W4F4Y9E7"
                        },
                        new
                        {
                            id = 3,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3763),
                            create_by = 14,
                            description = "Giao dịch thành công",
                            is_delete = false,
                            state = "thành công",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3764),
                            update_by = 14,
                            withdrawal_id = "3W3C1J8P1"
                        },
                        new
                        {
                            id = 4,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3766),
                            create_by = 14,
                            description = "Giao dịch thất bại",
                            is_delete = false,
                            state = "thất bại",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3767),
                            update_by = 14,
                            withdrawal_id = "4W6O2Q2R4"
                        },
                        new
                        {
                            id = 5,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3769),
                            create_by = 14,
                            description = "Giao dịch thành công",
                            is_delete = false,
                            state = "thành công",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3770),
                            update_by = 14,
                            withdrawal_id = "5W8O2W1A3"
                        },
                        new
                        {
                            id = 6,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3773),
                            create_by = 14,
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3774),
                            update_by = 14,
                            withdrawal_id = "6W2Z1O6B1"
                        },
                        new
                        {
                            id = 7,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3777),
                            create_by = 14,
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3777),
                            update_by = 14,
                            withdrawal_id = "7W3T0N3S0"
                        },
                        new
                        {
                            id = 8,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3780),
                            create_by = 14,
                            description = "Giao dịch thành công",
                            is_delete = false,
                            state = "thành công",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3781),
                            update_by = 14,
                            withdrawal_id = "8W4I2D8D0"
                        },
                        new
                        {
                            id = 9,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3783),
                            create_by = 14,
                            description = "Giao dịch thất bại",
                            is_delete = false,
                            state = "thất bại",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3784),
                            update_by = 14,
                            withdrawal_id = "9W6H6F3O2"
                        },
                        new
                        {
                            id = 10,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3787),
                            create_by = 14,
                            description = "Giao dịch thành công",
                            is_delete = false,
                            state = "thành công",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3788),
                            update_by = 14,
                            withdrawal_id = "10W1B4L3R5"
                        },
                        new
                        {
                            id = 11,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3790),
                            create_by = 14,
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3791),
                            update_by = 14,
                            withdrawal_id = "11W8I7T8V7"
                        },
                        new
                        {
                            id = 12,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3793),
                            create_by = 14,
                            description = "Đang xử lí",
                            is_delete = false,
                            state = "đang xử lí",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3794),
                            update_by = 14,
                            withdrawal_id = "12W6M7E2D3"
                        },
                        new
                        {
                            id = 13,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3796),
                            create_by = 14,
                            description = "Giao dịch thành công",
                            is_delete = false,
                            state = "thành công",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3797),
                            update_by = 14,
                            withdrawal_id = "13W4Q0L0L6"
                        },
                        new
                        {
                            id = 14,
                            create_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3799),
                            create_by = 14,
                            description = "Giao dịch thất bại",
                            is_delete = false,
                            state = "thất bại",
                            status = "đang xử lí",
                            type_transaction = "rút tiền",
                            update_at = new DateTime(2024, 3, 3, 23, 53, 27, 687, DateTimeKind.Local).AddTicks(3800),
                            update_by = 14,
                            withdrawal_id = "14W9C9M5F4"
                        });
                });

            modelBuilder.Entity("Business.Models.Wallet", b =>
                {
                    b.HasOne("Business.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Business.Models.Withdrawal", b =>
                {
                    b.HasOne("Business.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("wallet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
