// <auto-generated />
using System;
using BussinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BussinessObject.Migrations
{
    [DbContext(typeof(Web_Trung_GianContext))]
    [Migration("20240218064730_Init DB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BussinessObject.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2364),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Quốc tổ Hùng Vương",
                            password = "hungvuong123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2365),
                            username = "hungvuong"
                        },
                        new
                        {
                            id = 2,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2368),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Hai Bà Trưng",
                            password = "haibatrung123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2368),
                            username = "haibatrung"
                        },
                        new
                        {
                            id = 3,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2370),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Lý Nam Đế",
                            password = "lynamde123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2371),
                            username = "lynamde"
                        },
                        new
                        {
                            id = 4,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2373),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Ngô Quyền",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2373),
                            username = "ngoquyen"
                        },
                        new
                        {
                            id = 5,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2375),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Đinh Bộ Lĩnh",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2375),
                            username = "dinhbolinh"
                        },
                        new
                        {
                            id = 6,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2377),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Lê Hoàn",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2378),
                            username = "lehoan123"
                        },
                        new
                        {
                            id = 7,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2379),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Lý Công Uẩn",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2380),
                            username = "lyconguan"
                        },
                        new
                        {
                            id = 8,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2382),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Lý Thường Kiệt",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2383),
                            username = "lythuongkiet"
                        },
                        new
                        {
                            id = 9,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2385),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Trần Nhân Tông",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2385),
                            username = "trannhantong"
                        },
                        new
                        {
                            id = 10,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2387),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Trần Hưng Đạo",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2387),
                            username = "tranhungdao"
                        },
                        new
                        {
                            id = 11,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2389),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Lê Lợi",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2390),
                            username = "leloi123"
                        },
                        new
                        {
                            id = 12,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2392),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Trãi",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2392),
                            username = "nguyentrai"
                        },
                        new
                        {
                            id = 13,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2394),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Nguyễn Huệ",
                            password = "pass123",
                            phone = "0987654321",
                            role_id = 2,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2394),
                            username = "quangtrung"
                        },
                        new
                        {
                            id = 14,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2396),
                            email = "waterball208@gmail.com",
                            is_delete = false,
                            name = "Admin",
                            password = "admin",
                            phone = "0987654321",
                            role_id = 1,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2397),
                            username = "admin"
                        });
                });

            modelBuilder.Entity("BussinessObject.Models.AccountRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("desctiption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.ToTable("AccountRoles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            desctiption = "Admin"
                        },
                        new
                        {
                            id = 2,
                            desctiption = "User"
                        });
                });

            modelBuilder.Entity("BussinessObject.Models.Deposit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<string>("desctiption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("fee")
                        .HasColumnType("int");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.Property<int>("wallet_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("create_by");

                    b.HasIndex("update_by");

                    b.HasIndex("wallet_id");

                    b.ToTable("Deposits");

                    b.HasData(
                        new
                        {
                            id = 1,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2456),
                            create_by = 1,
                            fee = 500,
                            is_delete = false,
                            status = "done",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2457),
                            update_by = 1,
                            wallet_id = 1
                        },
                        new
                        {
                            id = 2,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2459),
                            create_by = 2,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2460),
                            update_by = 2,
                            wallet_id = 2
                        },
                        new
                        {
                            id = 3,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2461),
                            create_by = 3,
                            fee = 500,
                            is_delete = false,
                            status = "error",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2462),
                            update_by = 3,
                            wallet_id = 3
                        },
                        new
                        {
                            id = 4,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2464),
                            create_by = 4,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2465),
                            update_by = 4,
                            wallet_id = 4
                        },
                        new
                        {
                            id = 5,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2467),
                            create_by = 5,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2467),
                            update_by = 5,
                            wallet_id = 5
                        },
                        new
                        {
                            id = 6,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2469),
                            create_by = 6,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2469),
                            update_by = 6,
                            wallet_id = 6
                        },
                        new
                        {
                            id = 7,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2471),
                            create_by = 7,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2471),
                            update_by = 7,
                            wallet_id = 7
                        },
                        new
                        {
                            id = 8,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2473),
                            create_by = 8,
                            fee = 500,
                            is_delete = false,
                            status = "done",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2474),
                            update_by = 8,
                            wallet_id = 8
                        },
                        new
                        {
                            id = 9,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2475),
                            create_by = 9,
                            fee = 500,
                            is_delete = false,
                            status = "done",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2476),
                            update_by = 9,
                            wallet_id = 9
                        },
                        new
                        {
                            id = 10,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2478),
                            create_by = 10,
                            fee = 500,
                            is_delete = false,
                            status = "done",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2478),
                            update_by = 10,
                            wallet_id = 10
                        },
                        new
                        {
                            id = 11,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2480),
                            create_by = 11,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2480),
                            update_by = 11,
                            wallet_id = 11
                        },
                        new
                        {
                            id = 12,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2483),
                            create_by = 12,
                            fee = 500,
                            is_delete = false,
                            status = "error",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2484),
                            update_by = 12,
                            wallet_id = 12
                        },
                        new
                        {
                            id = 13,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2485),
                            create_by = 13,
                            fee = 500,
                            is_delete = false,
                            status = "error",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2486),
                            update_by = 13,
                            wallet_id = 13
                        },
                        new
                        {
                            id = 14,
                            amount = 10000,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2487),
                            create_by = 14,
                            fee = 500,
                            is_delete = false,
                            status = "done",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2488),
                            update_by = 14,
                            wallet_id = 14
                        });
                });

            modelBuilder.Entity("BussinessObject.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("total_price")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("account_id");

                    b.HasIndex("create_by");

                    b.HasIndex("product_id");

                    b.HasIndex("update_by");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BussinessObject.Models.ProcessedTransactionInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<string>("processed_message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("transaction_error_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("transaction_error_id");

                    b.ToTable("ProcessedTransactionInfos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2605),
                            create_by = 14,
                            processed_message = "Đã xử lí",
                            transaction_error_id = 4
                        },
                        new
                        {
                            id = 2,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2607),
                            create_by = 14,
                            processed_message = "Đã xử lí",
                            transaction_error_id = 3
                        },
                        new
                        {
                            id = 3,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2608),
                            create_by = 14,
                            processed_message = "Đã xử lí",
                            transaction_error_id = 1
                        },
                        new
                        {
                            id = 4,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2610),
                            create_by = 14,
                            processed_message = "Đã xử lí",
                            transaction_error_id = 2
                        });
                });

            modelBuilder.Entity("BussinessObject.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("categories")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<string>("desctiption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("image")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("create_by");

                    b.HasIndex("update_by");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            categories = 1,
                            code = "DH31UIHI3",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2558),
                            create_by = 14,
                            is_delete = false,
                            link = "#",
                            price = 1000,
                            quantity = 100,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2559),
                            update_by = 14
                        },
                        new
                        {
                            id = 2,
                            categories = 2,
                            code = "SOD2IF6AP8F",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2562),
                            create_by = 14,
                            is_delete = false,
                            link = "#",
                            price = 1000,
                            quantity = 100,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2562),
                            update_by = 14
                        },
                        new
                        {
                            id = 3,
                            categories = 3,
                            code = "AL6HEB14E",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2564),
                            create_by = 14,
                            is_delete = false,
                            link = "#",
                            price = 1000,
                            quantity = 100,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2565),
                            update_by = 14
                        },
                        new
                        {
                            id = 4,
                            categories = 1,
                            code = "IH189AOFA31OH",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2567),
                            create_by = 14,
                            is_delete = false,
                            link = "#",
                            price = 1000,
                            quantity = 100,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2567),
                            update_by = 14
                        },
                        new
                        {
                            id = 5,
                            categories = 2,
                            code = "JVY8F1KB4VOL",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2569),
                            create_by = 14,
                            is_delete = false,
                            link = "#",
                            price = 1000,
                            quantity = 100,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2569),
                            update_by = 14
                        },
                        new
                        {
                            id = 6,
                            categories = 3,
                            code = "PO0PM7MO9J",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2571),
                            create_by = 14,
                            is_delete = false,
                            link = "#",
                            price = 1000,
                            quantity = 100,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2572),
                            update_by = 14
                        },
                        new
                        {
                            id = 7,
                            categories = 1,
                            code = "ATF142DW4YT",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2574),
                            create_by = 14,
                            is_delete = false,
                            link = "#",
                            price = 1000,
                            quantity = 100,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2574),
                            update_by = 14
                        });
                });

            modelBuilder.Entity("BussinessObject.Models.TransactionError", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("wallet_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("wallet_id");

                    b.ToTable("TransactionErrors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2587),
                            create_by = 1,
                            description = "Lỗi Nạp tiền",
                            status = "done",
                            title = "Lỗi Nạp Tiền",
                            type = "Deposit",
                            wallet_id = 1
                        },
                        new
                        {
                            id = 2,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2589),
                            create_by = 4,
                            description = "Lỗi rút tiền",
                            status = "pending",
                            title = "Lỗi rút Tiền",
                            type = "Withdrawal",
                            wallet_id = 4
                        },
                        new
                        {
                            id = 3,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2591),
                            create_by = 7,
                            description = "Lỗi Nạp tiền",
                            status = "done",
                            title = "Lỗi Nạp Tiền",
                            type = "Deposit",
                            wallet_id = 7
                        },
                        new
                        {
                            id = 4,
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2593),
                            create_by = 10,
                            description = "Lỗi rút tiền",
                            status = "pending",
                            title = "Lỗi rút Tiền",
                            type = "Withdrawal",
                            wallet_id = 10
                        });
                });

            modelBuilder.Entity("BussinessObject.Models.Wallet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<int>("balance")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("account_id");

                    b.HasIndex("update_by");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            id = 1,
                            account_id = 1,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2415),
                            update_by = 1
                        },
                        new
                        {
                            id = 2,
                            account_id = 2,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2417),
                            update_by = 2
                        },
                        new
                        {
                            id = 3,
                            account_id = 3,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2418),
                            update_by = 3
                        },
                        new
                        {
                            id = 4,
                            account_id = 4,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2419),
                            update_by = 4
                        },
                        new
                        {
                            id = 5,
                            account_id = 5,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2420),
                            update_by = 5
                        },
                        new
                        {
                            id = 6,
                            account_id = 6,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2422),
                            update_by = 6
                        },
                        new
                        {
                            id = 7,
                            account_id = 7,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2423),
                            update_by = 7
                        },
                        new
                        {
                            id = 8,
                            account_id = 8,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2424),
                            update_by = 8
                        },
                        new
                        {
                            id = 9,
                            account_id = 9,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2425),
                            update_by = 9
                        },
                        new
                        {
                            id = 10,
                            account_id = 10,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2426),
                            update_by = 10
                        },
                        new
                        {
                            id = 11,
                            account_id = 11,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2428),
                            update_by = 11
                        },
                        new
                        {
                            id = 12,
                            account_id = 12,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2430),
                            update_by = 12
                        },
                        new
                        {
                            id = 13,
                            account_id = 13,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2431),
                            update_by = 13
                        },
                        new
                        {
                            id = 14,
                            account_id = 14,
                            balance = 10000,
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2432),
                            update_by = 14
                        });
                });

            modelBuilder.Entity("BussinessObject.Models.Withdrawal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("bank_name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("bank_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("bank_user")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("create_by")
                        .HasColumnType("int");

                    b.Property<int>("fee")
                        .HasColumnType("int");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.Property<int>("wallet_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("create_by");

                    b.HasIndex("update_by");

                    b.HasIndex("wallet_id");

                    b.ToTable("Withdrawals");

                    b.HasData(
                        new
                        {
                            id = 1,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Quốc Tổ Hùng Vương",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2507),
                            create_by = 1,
                            fee = 500,
                            is_delete = false,
                            status = "done",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2508),
                            update_by = 1,
                            wallet_id = 1
                        },
                        new
                        {
                            id = 2,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Hai Bà Trưng",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2511),
                            create_by = 2,
                            fee = 500,
                            is_delete = false,
                            status = "error",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2512),
                            update_by = 2,
                            wallet_id = 2
                        },
                        new
                        {
                            id = 3,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Lý Nam Đế",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2514),
                            create_by = 3,
                            fee = 500,
                            is_delete = false,
                            status = "done",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2514),
                            update_by = 3,
                            wallet_id = 3
                        },
                        new
                        {
                            id = 4,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2516),
                            create_by = 4,
                            fee = 500,
                            is_delete = false,
                            status = "error",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2517),
                            update_by = 4,
                            wallet_id = 4
                        },
                        new
                        {
                            id = 5,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2519),
                            create_by = 5,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2520),
                            update_by = 5,
                            wallet_id = 5
                        },
                        new
                        {
                            id = 6,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2521),
                            create_by = 6,
                            fee = 500,
                            is_delete = false,
                            status = "done",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2522),
                            update_by = 6,
                            wallet_id = 6
                        },
                        new
                        {
                            id = 7,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2524),
                            create_by = 7,
                            fee = 500,
                            is_delete = false,
                            status = "done",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2524),
                            update_by = 7,
                            wallet_id = 7
                        },
                        new
                        {
                            id = 8,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2526),
                            create_by = 8,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2527),
                            update_by = 8,
                            wallet_id = 8
                        },
                        new
                        {
                            id = 9,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2529),
                            create_by = 9,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2530),
                            update_by = 9,
                            wallet_id = 9
                        },
                        new
                        {
                            id = 10,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2532),
                            create_by = 10,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2532),
                            update_by = 10,
                            wallet_id = 10
                        },
                        new
                        {
                            id = 11,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2534),
                            create_by = 11,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2535),
                            update_by = 11,
                            wallet_id = 11
                        },
                        new
                        {
                            id = 12,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2536),
                            create_by = 12,
                            fee = 500,
                            is_delete = false,
                            status = "done",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2537),
                            update_by = 12,
                            wallet_id = 12
                        },
                        new
                        {
                            id = 13,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2539),
                            create_by = 13,
                            fee = 500,
                            is_delete = false,
                            status = "pending",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2539),
                            update_by = 13,
                            wallet_id = 13
                        },
                        new
                        {
                            id = 14,
                            amount = 10000,
                            bank_name = "TP Bank",
                            bank_number = "789654312",
                            bank_user = "Bank User Name",
                            create_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2541),
                            create_by = 14,
                            fee = 500,
                            is_delete = false,
                            status = "error",
                            update_at = new DateTime(2024, 2, 18, 13, 47, 30, 347, DateTimeKind.Local).AddTicks(2542),
                            update_by = 14,
                            wallet_id = 14
                        });
                });

            modelBuilder.Entity("BussinessObject.Models.Account", b =>
                {
                    b.HasOne("BussinessObject.Models.AccountRole", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BussinessObject.Models.Deposit", b =>
                {
                    b.HasOne("BussinessObject.Models.Account", "AccountCreate")
                        .WithMany("DepositCreates")
                        .HasForeignKey("create_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Account", "AccountUpdate")
                        .WithMany("DepositUpdates")
                        .HasForeignKey("update_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Wallet", "Wallet")
                        .WithMany("Deposits")
                        .HasForeignKey("wallet_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountCreate");

                    b.Navigation("AccountUpdate");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("BussinessObject.Models.Order", b =>
                {
                    b.HasOne("BussinessObject.Models.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Account", "AccountCreate")
                        .WithMany("OrderCreates")
                        .HasForeignKey("create_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Account", "AccountUpdate")
                        .WithMany("OrderUpdate")
                        .HasForeignKey("update_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AccountCreate");

                    b.Navigation("AccountUpdate");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BussinessObject.Models.ProcessedTransactionInfo", b =>
                {
                    b.HasOne("BussinessObject.Models.TransactionError", "TransactionError")
                        .WithMany("ProcessedTransactionInfos")
                        .HasForeignKey("transaction_error_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransactionError");
                });

            modelBuilder.Entity("BussinessObject.Models.Product", b =>
                {
                    b.HasOne("BussinessObject.Models.Account", "AccountCreate")
                        .WithMany("ProductCreates")
                        .HasForeignKey("create_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Account", "AccountUpdate")
                        .WithMany("ProductUpdates")
                        .HasForeignKey("update_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountCreate");

                    b.Navigation("AccountUpdate");
                });

            modelBuilder.Entity("BussinessObject.Models.TransactionError", b =>
                {
                    b.HasOne("BussinessObject.Models.Wallet", "Wallet")
                        .WithMany("TransactionErrors")
                        .HasForeignKey("wallet_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("BussinessObject.Models.Wallet", b =>
                {
                    b.HasOne("BussinessObject.Models.Account", "Account")
                        .WithMany("Wallets")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Account", "AccountUpdate")
                        .WithMany("WalletUpdates")
                        .HasForeignKey("update_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AccountUpdate");
                });

            modelBuilder.Entity("BussinessObject.Models.Withdrawal", b =>
                {
                    b.HasOne("BussinessObject.Models.Account", "AccountCreate")
                        .WithMany("WithdrawalCreates")
                        .HasForeignKey("create_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Account", "AccountUpdate")
                        .WithMany("WithdrawalUpdates")
                        .HasForeignKey("update_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BussinessObject.Models.Wallet", "Wallet")
                        .WithMany("Withdrawals")
                        .HasForeignKey("wallet_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountCreate");

                    b.Navigation("AccountUpdate");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("BussinessObject.Models.Account", b =>
                {
                    b.Navigation("DepositCreates");

                    b.Navigation("DepositUpdates");

                    b.Navigation("OrderCreates");

                    b.Navigation("OrderUpdate");

                    b.Navigation("Orders");

                    b.Navigation("ProductCreates");

                    b.Navigation("ProductUpdates");

                    b.Navigation("WalletUpdates");

                    b.Navigation("Wallets");

                    b.Navigation("WithdrawalCreates");

                    b.Navigation("WithdrawalUpdates");
                });

            modelBuilder.Entity("BussinessObject.Models.AccountRole", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BussinessObject.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BussinessObject.Models.TransactionError", b =>
                {
                    b.Navigation("ProcessedTransactionInfos");
                });

            modelBuilder.Entity("BussinessObject.Models.Wallet", b =>
                {
                    b.Navigation("Deposits");

                    b.Navigation("TransactionErrors");

                    b.Navigation("Withdrawals");
                });
#pragma warning restore 612, 618
        }
    }
}
